name: dart_toast
description: Support for simple toast messages in Dart web apps.
version: 0.1.0
author: Monty Rasmussen
homepage: github.com/montyr75/dart_toast

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  css_animation: ^0.1.8

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.3
